# Generated by Django 5.0.3 on 2025-03-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_approval_date_user_banned_date_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
