# Generated by Django 5.0.3 on 2025-03-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_admin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_status',
            field=models.CharField(blank=True, choices=[('No Request', None), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('No Request', None), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10, null=True),
        ),
    ]
