# Generated by Django 5.0.3 on 2025-03-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0002_adminverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorverification',
            name='documents',
        ),
        migrations.AddField(
            model_name='instructorverification',
            name='aadhar_number',
            field=models.CharField(default=None, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='instructorverification',
            name='account_number',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='instructorverification',
            name='pan_number',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='adminverification',
            name='admin_status',
            field=models.CharField(choices=[('no_request', 'No Request'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='no_request', max_length=10),
        ),
        migrations.AlterField(
            model_name='instructorverification',
            name='status',
            field=models.CharField(choices=[('no_request', 'No Request'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='no_request', max_length=20),
        ),
    ]
