# Generated by Django 5.0.3 on 2025-02-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='lesson',
            name='extra_sections',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pdf_files',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
